version: "3.8"

services:
  # oapi-codegen
  oapi-codegen:
    image: ${PROJECT_NAME}:go-${DOCKER_BUILD_TAG_VERSION}
    build: ./docker/deps/
    volumes:
      - ${SPEC_DIR}:/api
    entrypoint: /go/bin/oapi-codegen

  openapi-generator-cli:
    # TODO: upgrade openapi-generator-cli latest version
    image: openapitools/openapi-generator-cli:v5.3.0
    volumes:
      - ${SPEC_DIR}:/api