version: "3.8"

services:
  # oapi-codegen
  oapi-codegen:
    image: ${PROJECT_NAME}:go-${DOCKER_BUILD_TAG_VERSION}
    build: ./docker/deps/
    volumes:
      - ${SPEC_DIR}:/api
    entrypoint: /go/bin/oapi-codegen

  openapi-generator-cli:
    # TODO: upgrade openapi-generator-cli latest version
    image: openapitools/openapi-generator-cli:v5.3.0
    volumes:
      - ${SPEC_DIR}:/api

  # go mod
  # usage: docker-compose -f docker-compose-tools.yml run --rm -v "${SRC_DIR}":${GOPATH} -w ${GOPATH} go-mod
  go-mod:
    image: ${PROJECT_NAME}:go-${DOCKER_BUILD_TAG_VERSION}
    build: ./docker/deps/
    command: sh -c "go mod tidy && go mod vendor"

  # go generate
  # usage: docker-compose -f docker-compose-tools.yml run --rm -v "${SRC_DIR}":${GOPATH} -w ${GOPATH} go-generate
  go-generate:
    image: ${PROJECT_NAME}:go-${DOCKER_BUILD_TAG_VERSION}
    build: ./docker/deps/
    command: go generate ./...

  go-fmt:
    image: ${PROJECT_NAME}:go-${DOCKER_BUILD_TAG_VERSION}
    build: ./docker/deps/
    command: sh -c "go fmt ./... && find . -name \*.go -not -path '\./vendor/*' -not -path '\./gen/*' | xargs goimports -w -local 'github.com/moneyforward/mfc_project_master'"

  # go test
  # usage: docker-compose -f docker-compose-tools.yml run --rm -v "${SRC_DIR}":${GOPATH} -w ${GOPATH} go-test
  go-test:
    image: golangci/golangci-lint:v1.59.0-alpine
    entrypoint: sh ./test.sh

  # go lint
  # usage: docker-compose -f docker-compose-tools.yml run --rm -v "${SRC_DIR}":${GOPATH} -w ${GOPATH} go-lint
  go-lint:
    image: golangci/golangci-lint:v1.59.0-alpine
    command: golangci-lint run --config .golangci.yml
    environment: [GO111MODULE=on]

  # buf
  buf-generate:
    image: bufbuild/buf:latest
    command: generate
  buf-lint:
    image: bufbuild/buf:latest
    command: lint
