version: '3.8'

x-env: &appenv
  environment:
    - DB_HOST=${MYSQL_CONTAINER_NAME}
    - DB_PORT=3306
    - DB_USER=${MYSQL_USER}
    - DB_PASS=${MYSQL_PASSWORD}
    - DB_NAME=${MYSQL_DATABASE}
services:
  db:
    image: mysql:8.4.2
    command: ["mysqld", "--mysql-native-password=ON"]
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d/
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    restart: always
    container_name: ${PROJECT_NAME}-db

  app-api-internal_api:
    image: ${PROJECT_NAME}:go-delve-${DOCKER_BUILD_TAG_VERSION}
    build: ./docker/delve
    command: air -c .air-internal_api.toml
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ${APP_API_ROOT}:${APP_API_GOPATH}
    working_dir: ${APP_API_GOPATH}
    <<: *appenv
    depends_on:
      - db
    restart: always
    container_name: ${PROJECT_NAME}-app-api-internal_api

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
