version: "3.8"

services:

  # migrate
  flyway:
    image: flyway/flyway:10-alpine
    command: info
    volumes:
      - ./database:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?charset=utf8mb4&collation=utf8mb4_bin&parseTime=true&allowPublicKeyRetrieval=true
      - FLYWAY_SCHEMAS=${MYSQL_DATABASE}
      - FLYWAY_USER=${MYSQL_USER}
      - FLYWAY_PASSWORD=${MYSQL_PASSWORD}
      - FLYWAY_LOCATIONS=filesystem:sql/migrations
      - FLYWAY_ENCODING=UTF-8
      - FLYWAY_CLEAN_DISABLED=false
