// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameClient = "clients"

// Client mapped from table <clients>
type Client struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClientID     string    `gorm:"column:client_id;not null" json:"client_id"`
	EditingStyle string    `gorm:"column:editing_style" json:"editing_style"`
	Requirements string    `gorm:"column:requirements" json:"requirements"`
	Others       string    `gorm:"column:others" json:"others"`
	IsActive     bool      `gorm:"column:is_active;not null;default:1" json:"is_active"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName Client's table name
func (*Client) TableName() string {
	return TableNameClient
}
