// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TicketID  int64     `gorm:"column:ticket_id;not null" json:"ticket_id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	Comment   string    `gorm:"column:comment;not null" json:"comment"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
