// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistory = "histories"

// History mapped from table <histories>
type History struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TicketID    int64     `gorm:"column:ticket_id;not null" json:"ticket_id"`
	Action      string    `gorm:"column:action" json:"action"`
	PerformedBy string    `gorm:"column:performed_by;not null" json:"performed_by"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	NickName    string    `gorm:"-"`
}

// TableName History's table name
func (*History) TableName() string {
	return TableNameHistory
}
