// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNasServer = "nas_servers"

// NasServer mapped from table <nas_servers>
type NasServer struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NasID        int32     `gorm:"column:nas_id;not null" json:"nas_id"`
	Name         string    `gorm:"column:name" json:"name"`
	RootPath     string    `gorm:"column:root_path" json:"root_path"`
	InternalPath string    `gorm:"column:internal_path" json:"internal_path"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName NasServer's table name
func (*NasServer) TableName() string {
	return TableNameNasServer
}
