// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNasRequest = "nas_requests"

// NasRequest mapped from table <nas_requests>
type NasRequest struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NasID     int32     `gorm:"column:nas_id;not null" json:"nas_id"`
	Payload   string    `gorm:"column:payload" json:"payload"`
	Status    string    `gorm:"column:status;not null" json:"status"`
	Error     string    `gorm:"column:error" json:"error"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName NasRequest's table name
func (*NasRequest) TableName() string {
	return TableNameNasRequest
}
