// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "sessions"

// Session mapped from table <sessions>
type Session struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SessionID    string    `gorm:"column:session_id;not null" json:"session_id"`
	UserID       string    `gorm:"column:user_id;not null" json:"user_id"`
	RefreshToken string    `gorm:"column:refresh_token;not null" json:"refresh_token"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	ExpiredAt    time.Time `gorm:"column:expired_at;not null" json:"expired_at"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
