// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTicket = "tickets"

// Ticket mapped from table <tickets>
type Ticket struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Status      string    `gorm:"column:status;not null" json:"status"`
	QcID        string    `gorm:"column:qc_id;not null" json:"qc_id"`
	EditorID    string    `gorm:"column:editor_id;not null" json:"editor_id"`
	Priority    string    `gorm:"column:priority;not null;default:NORMAL" json:"priority"`
	ClientID    int32     `gorm:"column:client_id;not null" json:"client_id"`
	Description string    `gorm:"column:description" json:"description"`
	CreatedBy   string    `gorm:"column:created_by;not null;default:AUTO" json:"created_by"`
	IsActive    bool      `gorm:"column:is_active;not null;default:1" json:"is_active"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName Ticket's table name
func (*Ticket) TableName() string {
	return TableNameTicket
}
