// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         string    `gorm:"column:user_id;not null" json:"user_id"`
	NickName       string    `gorm:"column:nick_name;not null" json:"nick_name"`
	Email          string    `gorm:"column:email;not null" json:"email"`
	PasswordHashed string    `gorm:"column:password_hashed;not null" json:"password_hashed"`
	ContractType   string    `gorm:"column:contract_type;not null;default:FULLTIME" json:"contract_type"`
	IsActive       []uint8   `gorm:"column:is_active;not null;default:b'1'" json:"is_active"`
	IsAdmin        []uint8   `gorm:"column:is_admin;not null;default:b'0'" json:"is_admin"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
