// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Haevnen/p2m_be/internal/pkg/model"
)

func newNasServer(db *gorm.DB, opts ...gen.DOOption) nasServer {
	_nasServer := nasServer{}

	_nasServer.nasServerDo.UseDB(db, opts...)
	_nasServer.nasServerDo.UseModel(&model.NasServer{})

	tableName := _nasServer.nasServerDo.TableName()
	_nasServer.ALL = field.NewAsterisk(tableName)
	_nasServer.ID = field.NewInt64(tableName, "id")
	_nasServer.NasID = field.NewInt32(tableName, "nas_id")
	_nasServer.Name = field.NewString(tableName, "name")
	_nasServer.RootPath = field.NewString(tableName, "root_path")
	_nasServer.InternalPath = field.NewString(tableName, "internal_path")
	_nasServer.CreatedAt = field.NewTime(tableName, "created_at")

	_nasServer.fillFieldMap()

	return _nasServer
}

type nasServer struct {
	nasServerDo nasServerDo

	ALL          field.Asterisk
	ID           field.Int64
	NasID        field.Int32
	Name         field.String
	RootPath     field.String
	InternalPath field.String
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (n nasServer) Table(newTableName string) *nasServer {
	n.nasServerDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nasServer) As(alias string) *nasServer {
	n.nasServerDo.DO = *(n.nasServerDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nasServer) updateTableName(table string) *nasServer {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NasID = field.NewInt32(table, "nas_id")
	n.Name = field.NewString(table, "name")
	n.RootPath = field.NewString(table, "root_path")
	n.InternalPath = field.NewString(table, "internal_path")
	n.CreatedAt = field.NewTime(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *nasServer) WithContext(ctx context.Context) *nasServerDo {
	return n.nasServerDo.WithContext(ctx)
}

func (n nasServer) TableName() string { return n.nasServerDo.TableName() }

func (n nasServer) Alias() string { return n.nasServerDo.Alias() }

func (n nasServer) Columns(cols ...field.Expr) gen.Columns { return n.nasServerDo.Columns(cols...) }

func (n *nasServer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nasServer) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["id"] = n.ID
	n.fieldMap["nas_id"] = n.NasID
	n.fieldMap["name"] = n.Name
	n.fieldMap["root_path"] = n.RootPath
	n.fieldMap["internal_path"] = n.InternalPath
	n.fieldMap["created_at"] = n.CreatedAt
}

func (n nasServer) clone(db *gorm.DB) nasServer {
	n.nasServerDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nasServer) replaceDB(db *gorm.DB) nasServer {
	n.nasServerDo.ReplaceDB(db)
	return n
}

type nasServerDo struct{ gen.DO }

func (n nasServerDo) Debug() *nasServerDo {
	return n.withDO(n.DO.Debug())
}

func (n nasServerDo) WithContext(ctx context.Context) *nasServerDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nasServerDo) ReadDB() *nasServerDo {
	return n.Clauses(dbresolver.Read)
}

func (n nasServerDo) WriteDB() *nasServerDo {
	return n.Clauses(dbresolver.Write)
}

func (n nasServerDo) Session(config *gorm.Session) *nasServerDo {
	return n.withDO(n.DO.Session(config))
}

func (n nasServerDo) Clauses(conds ...clause.Expression) *nasServerDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nasServerDo) Returning(value interface{}, columns ...string) *nasServerDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nasServerDo) Not(conds ...gen.Condition) *nasServerDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nasServerDo) Or(conds ...gen.Condition) *nasServerDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nasServerDo) Select(conds ...field.Expr) *nasServerDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nasServerDo) Where(conds ...gen.Condition) *nasServerDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nasServerDo) Order(conds ...field.Expr) *nasServerDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nasServerDo) Distinct(cols ...field.Expr) *nasServerDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nasServerDo) Omit(cols ...field.Expr) *nasServerDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nasServerDo) Join(table schema.Tabler, on ...field.Expr) *nasServerDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nasServerDo) LeftJoin(table schema.Tabler, on ...field.Expr) *nasServerDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nasServerDo) RightJoin(table schema.Tabler, on ...field.Expr) *nasServerDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nasServerDo) Group(cols ...field.Expr) *nasServerDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nasServerDo) Having(conds ...gen.Condition) *nasServerDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nasServerDo) Limit(limit int) *nasServerDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nasServerDo) Offset(offset int) *nasServerDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nasServerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *nasServerDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nasServerDo) Unscoped() *nasServerDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nasServerDo) Create(values ...*model.NasServer) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nasServerDo) CreateInBatches(values []*model.NasServer, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nasServerDo) Save(values ...*model.NasServer) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nasServerDo) First() (*model.NasServer, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasServer), nil
	}
}

func (n nasServerDo) Take() (*model.NasServer, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasServer), nil
	}
}

func (n nasServerDo) Last() (*model.NasServer, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasServer), nil
	}
}

func (n nasServerDo) Find() ([]*model.NasServer, error) {
	result, err := n.DO.Find()
	return result.([]*model.NasServer), err
}

func (n nasServerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NasServer, err error) {
	buf := make([]*model.NasServer, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nasServerDo) FindInBatches(result *[]*model.NasServer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nasServerDo) Attrs(attrs ...field.AssignExpr) *nasServerDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nasServerDo) Assign(attrs ...field.AssignExpr) *nasServerDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nasServerDo) Joins(fields ...field.RelationField) *nasServerDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nasServerDo) Preload(fields ...field.RelationField) *nasServerDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nasServerDo) FirstOrInit() (*model.NasServer, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasServer), nil
	}
}

func (n nasServerDo) FirstOrCreate() (*model.NasServer, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasServer), nil
	}
}

func (n nasServerDo) FindByPage(offset int, limit int) (result []*model.NasServer, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nasServerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nasServerDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nasServerDo) Delete(models ...*model.NasServer) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nasServerDo) withDO(do gen.Dao) *nasServerDo {
	n.DO = *do.(*gen.DO)
	return n
}
