// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Haevnen/p2m_be/internal/pkg/model"
)

func newNasRequest(db *gorm.DB, opts ...gen.DOOption) nasRequest {
	_nasRequest := nasRequest{}

	_nasRequest.nasRequestDo.UseDB(db, opts...)
	_nasRequest.nasRequestDo.UseModel(&model.NasRequest{})

	tableName := _nasRequest.nasRequestDo.TableName()
	_nasRequest.ALL = field.NewAsterisk(tableName)
	_nasRequest.ID = field.NewInt64(tableName, "id")
	_nasRequest.NasID = field.NewInt32(tableName, "nas_id")
	_nasRequest.Payload = field.NewString(tableName, "payload")
	_nasRequest.Status = field.NewString(tableName, "status")
	_nasRequest.Error = field.NewString(tableName, "error")
	_nasRequest.CreatedAt = field.NewTime(tableName, "created_at")

	_nasRequest.fillFieldMap()

	return _nasRequest
}

type nasRequest struct {
	nasRequestDo nasRequestDo

	ALL       field.Asterisk
	ID        field.Int64
	NasID     field.Int32
	Payload   field.String
	Status    field.String
	Error     field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (n nasRequest) Table(newTableName string) *nasRequest {
	n.nasRequestDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nasRequest) As(alias string) *nasRequest {
	n.nasRequestDo.DO = *(n.nasRequestDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nasRequest) updateTableName(table string) *nasRequest {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NasID = field.NewInt32(table, "nas_id")
	n.Payload = field.NewString(table, "payload")
	n.Status = field.NewString(table, "status")
	n.Error = field.NewString(table, "error")
	n.CreatedAt = field.NewTime(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *nasRequest) WithContext(ctx context.Context) *nasRequestDo {
	return n.nasRequestDo.WithContext(ctx)
}

func (n nasRequest) TableName() string { return n.nasRequestDo.TableName() }

func (n nasRequest) Alias() string { return n.nasRequestDo.Alias() }

func (n nasRequest) Columns(cols ...field.Expr) gen.Columns { return n.nasRequestDo.Columns(cols...) }

func (n *nasRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nasRequest) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["id"] = n.ID
	n.fieldMap["nas_id"] = n.NasID
	n.fieldMap["payload"] = n.Payload
	n.fieldMap["status"] = n.Status
	n.fieldMap["error"] = n.Error
	n.fieldMap["created_at"] = n.CreatedAt
}

func (n nasRequest) clone(db *gorm.DB) nasRequest {
	n.nasRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nasRequest) replaceDB(db *gorm.DB) nasRequest {
	n.nasRequestDo.ReplaceDB(db)
	return n
}

type nasRequestDo struct{ gen.DO }

func (n nasRequestDo) Debug() *nasRequestDo {
	return n.withDO(n.DO.Debug())
}

func (n nasRequestDo) WithContext(ctx context.Context) *nasRequestDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nasRequestDo) ReadDB() *nasRequestDo {
	return n.Clauses(dbresolver.Read)
}

func (n nasRequestDo) WriteDB() *nasRequestDo {
	return n.Clauses(dbresolver.Write)
}

func (n nasRequestDo) Session(config *gorm.Session) *nasRequestDo {
	return n.withDO(n.DO.Session(config))
}

func (n nasRequestDo) Clauses(conds ...clause.Expression) *nasRequestDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nasRequestDo) Returning(value interface{}, columns ...string) *nasRequestDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nasRequestDo) Not(conds ...gen.Condition) *nasRequestDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nasRequestDo) Or(conds ...gen.Condition) *nasRequestDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nasRequestDo) Select(conds ...field.Expr) *nasRequestDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nasRequestDo) Where(conds ...gen.Condition) *nasRequestDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nasRequestDo) Order(conds ...field.Expr) *nasRequestDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nasRequestDo) Distinct(cols ...field.Expr) *nasRequestDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nasRequestDo) Omit(cols ...field.Expr) *nasRequestDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nasRequestDo) Join(table schema.Tabler, on ...field.Expr) *nasRequestDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nasRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) *nasRequestDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nasRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) *nasRequestDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nasRequestDo) Group(cols ...field.Expr) *nasRequestDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nasRequestDo) Having(conds ...gen.Condition) *nasRequestDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nasRequestDo) Limit(limit int) *nasRequestDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nasRequestDo) Offset(offset int) *nasRequestDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nasRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *nasRequestDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nasRequestDo) Unscoped() *nasRequestDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nasRequestDo) Create(values ...*model.NasRequest) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nasRequestDo) CreateInBatches(values []*model.NasRequest, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nasRequestDo) Save(values ...*model.NasRequest) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nasRequestDo) First() (*model.NasRequest, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasRequest), nil
	}
}

func (n nasRequestDo) Take() (*model.NasRequest, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasRequest), nil
	}
}

func (n nasRequestDo) Last() (*model.NasRequest, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasRequest), nil
	}
}

func (n nasRequestDo) Find() ([]*model.NasRequest, error) {
	result, err := n.DO.Find()
	return result.([]*model.NasRequest), err
}

func (n nasRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NasRequest, err error) {
	buf := make([]*model.NasRequest, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nasRequestDo) FindInBatches(result *[]*model.NasRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nasRequestDo) Attrs(attrs ...field.AssignExpr) *nasRequestDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nasRequestDo) Assign(attrs ...field.AssignExpr) *nasRequestDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nasRequestDo) Joins(fields ...field.RelationField) *nasRequestDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nasRequestDo) Preload(fields ...field.RelationField) *nasRequestDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nasRequestDo) FirstOrInit() (*model.NasRequest, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasRequest), nil
	}
}

func (n nasRequestDo) FirstOrCreate() (*model.NasRequest, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NasRequest), nil
	}
}

func (n nasRequestDo) FindByPage(offset int, limit int) (result []*model.NasRequest, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nasRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nasRequestDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nasRequestDo) Delete(models ...*model.NasRequest) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nasRequestDo) withDO(do gen.Dao) *nasRequestDo {
	n.DO = *do.(*gen.DO)
	return n
}
