name: Deployment in Staging

on:
  push:
    branches:
      - main

jobs:
  deploy-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/setup-go@v5

      - name: Pull Flyway Docker image
        run: |
          docker pull flyway/flyway:10-alpine

      - name: Setup environment
        run: |
          echo "FLYWAY_URL=${{ secrets.FLYWAY_STG_URL }}" >> $GITHUB_ENV
          echo "FLYWAY_USER=${{ secrets.FLYWAY_USER }}" >> $GITHUB_ENV
          echo "FLYWAY_PASSWORD=${{ secrets.FLYWAY_STG_PASSWORD }}" >> $GITHUB_ENV
          echo "FLYWAY_SCHEMAS=p2m_db" >> $GITHUB_ENV
          echo "FLYWAY_LOCATIONS=filesystem:database/migrations" >> $GITHUB_ENV

      - name: Run Flyway migrations using Docker
        run: |
          docker run --rm \
            -v $(pwd)/database:/flyway/sql \
            -e FLYWAY_URL=$FLYWAY_URL\
            -e FLYWAY_USER=$FLYWAY_USER \
            -e FLYWAY_PASSWORD=$FLYWAY_PASSWORD \
            -e FLYWAY_SCHEMAS=p2m_db \
            -e FLYWAY_LOCATIONS=filesystem:sql/migrations \
            flyway/flyway:10-alpine migrate

      - name: Clean up Docker image
        run: |
          docker rmi flyway/flyway:10-alpine || true

  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -gcflags "all=-N -l" -o internal_api ./cmd/p2m_api/main.go

      - name: Overwrite Environment variables
        run: |
          echo "DB_PORT=${{ secrets.DB_PORT_STG }}" > .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.FLYWAY_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.FLYWAY_STG_PASSWORD }}" >> .env
          echo "API_PORT=${{ secrets.API_PORT_STG }}" >> .env
          echo "API_HOST=${{ secrets.API_HOST }}" >> .env
          echo "RUN_MODE=${{ secrets.RUN_MODE_STG }}" >> .env

      - name: Transfer files to server
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          API_HOST: ${{ secrets.API_HOST }}
        run : |
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no internal_api .env root@$API_HOST:/root/p2m_stg_tmp
          
      - name: Update service
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          API_HOST: ${{ secrets.API_HOST }}
          API_STG_SERVICE_NAME: ${{ secrets.API_STG_SERVICE_NAME }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no -T root@$API_HOST << EOF
            sudo systemctl stop $API_STG_SERVICE_NAME
            cp /root/p2m_stg_tmp/.env /root/p2m_stg_tmp/internal_api /root/p2m_stg/
            sudo systemctl start $API_STG_SERVICE_NAME
          EOF
