name: Deployment in Production

on:
  push:
    branches:
      - release

jobs:
  deploy-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Flyway Docker image
        run: |
          docker pull flyway/flyway:10-alpine

      - name: Setup environment
        run: |
          echo "FLYWAY_URL=${{ secrets.FLYWAY_PROD_URL }}" >> $GITHUB_ENV
          echo "FLYWAY_USER=${{ secrets.FLYWAY_USER }}" >> $GITHUB_ENV
          echo "FLYWAY_PASSWORD=${{ secrets.FLYWAY_PROD_PASSWORD }}" >> $GITHUB_ENV
          echo "FLYWAY_SCHEMAS=p2m_db" >> $GITHUB_ENV
          echo "FLYWAY_LOCATIONS=filesystem:database/migrations" >> $GITHUB_ENV

      - name: Run Flyway migrations using Docker
        run: |
          docker run --rm \
            -v $(pwd)/database:/flyway/sql \
            -e FLYWAY_URL=$FLYWAY_URL\
            -e FLYWAY_USER=$FLYWAY_USER \
            -e FLYWAY_PASSWORD=$FLYWAY_PASSWORD \
            -e FLYWAY_SCHEMAS=p2m_db \
            -e FLYWAY_LOCATIONS=filesystem:sql/migrations \
            flyway/flyway:10-alpine migrate

      - name: Clean up Docker image
        run: |
          docker rmi flyway/flyway:10-alpine || true

  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -gcflags "all=-N -l" -o internal_api ./cmd/p2m_api/main.go

      - name: Overwrite Environment variables
        run: |
          echo "DB_PORT=${{ secrets.DB_PORT_PROD }}" > .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.FLYWAY_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.FLYWAY_PROD_PASSWORD }}" >> .env
          echo "API_PORT=${{ secrets.API_PORT_PROD }}" >> .env
          echo "API_HOST=${{ secrets.API_HOST }}" >> .env
          echo "RUN_MODE=${{ secrets.RUN_MODE_PROD }}" >> .env
          echo "LOG_PATH"=${{ secrets.LOG_PATH }} >> .env
          echo "TOKEN_SYMMETRIC_KEY"=${{ secrets.TOKEN_SYMMETRIC_KEY }} >> .env

      - name: Transfer files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: $API_HOST
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "internal_api, .env"
          target: /root/p2m_prod_tmp
          
      - name: Update service
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          API_HOST: ${{ secrets.API_HOST }}
          API_PROD_SERVICE_NAME: ${{ secrets.API_PROD_SERVICE_NAME }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no -T root@$API_HOST << EOF
            sudo systemctl stop $API_PROD_SERVICE_NAME
            cp /root/p2m_prod_tmp/.env /root/p2m_prod_tmp/internal_api /root/p2m_prod/
            sudo systemctl start $API_PROD_SERVICE_NAME
            sudo systemctl status $API_PROD_SERVICE_NAME
          EOF
